"""
Interactive page configuration manager.

Refactored from the original book_automation.py:
- JSON as source of truth (no more regex-based JS parsing)
- JS file is generated output, not input
- Cleaner interactive prompts with validation
"""
import json
import logging
import sys
from pathlib import Path

from src.config.settings import (
    BASE_DIR, SOUNDS_DIR, JS_DIR, PAGE_CONFIG_FILE, LOG_LEVEL, LOG_FORMAT
)

logging.basicConfig(level=getattr(logging, LOG_LEVEL), format=LOG_FORMAT)
logger = logging.getLogger(__name__)

# Source-of-truth config stored as JSON alongside the repo
CONFIG_DATA_FILE = BASE_DIR / "page_config_data.json"


def load_config() -> dict:
    """Load existing config or return a fresh empty skeleton."""
    if CONFIG_DATA_FILE.exists():
        return json.loads(CONFIG_DATA_FILE.read_text(encoding="utf-8"))
    return {"pages": {}, "sectionToPageMap": {}}


def save_config(config: dict) -> None:
    """Persist config to page_config_data.json."""
    CONFIG_DATA_FILE.write_text(
        json.dumps(config, ensure_ascii=False, indent=2), encoding="utf-8"
    )


def get_available_sections() -> list:
    """List section IDs found in all_sounds/."""
    if not SOUNDS_DIR.is_dir():
        return []
    return sorted(d.name for d in SOUNDS_DIR.iterdir() if d.is_dir())


def prompt_sections(available: list) -> list:
    """Interactively prompt user to pick sections for a page."""
    print("\nAvailable sections:", ", ".join(available))
    raw = input("Enter sections for this page (comma-separated, e.g. 1.1,1.2): ").strip()
    sections = [s.strip() for s in raw.split(",") if s.strip()]
    invalid = [s for s in sections if s not in available]
    if invalid:
        print(f"Warning: sections not found in all_sounds/: {invalid}")
    return sections


def add_page(config: dict) -> dict:
    """Interactively add a new page configuration entry."""
    page_num = input("PDF page number (integer): ").strip()
    if not page_num.isdigit():
        print("Invalid page number.")
        return config

    available = get_available_sections()
    sections = prompt_sections(available)
    if not sections:
        print("No sections selected.")
        return config

    title = input("Page title (e.g. 'Human Body'): ").strip()
    description = input("Page description (optional): ").strip()
    primary = sections[0]

    config["pages"][page_num] = {
        "pageNumber": int(page_num),
        "sections": sections,
        "dataFile": f"extracted_words/extracted_words_page{page_num}.json",
        "imageFile": f"images/page{page_num}.png",
        "title": title,
        "description": description,
        "primarySection": primary,
    }
    for sec in sections:
        config["sectionToPageMap"][sec] = int(page_num)

    return config


def generate_js(config: dict) -> str:
    """Generate page-config.js content from the JSON config dict."""
    pages_js = json.dumps(config["pages"], ensure_ascii=False, indent=4)
    section_map_js = json.dumps(config["sectionToPageMap"], ensure_ascii=False, indent=4)

    return f"""// AUTO-GENERATED by tools/book_automation.py — do not edit manually
// Edit page_config_data.json and re-run tools/book_automation.py instead
class PageConfigManager {{
    pageConfigs = {pages_js};
    sectionToPageMap = {section_map_js};

    getPageConfig(pageOrSection) {{
        if (typeof pageOrSection === 'number') return this.pageConfigs[pageOrSection];
        const page = this.sectionToPageMap[pageOrSection];
        return page !== undefined ? this.pageConfigs[page] : null;
    }}

    getAllPageConfigs() {{
        return Object.values(this.pageConfigs);
    }}
}}
const pageConfigManager = new PageConfigManager();
"""


def main():
    config = load_config()
    print(f"Loaded config: {len(config['pages'])} pages")

    while True:
        print("\n[a] Add page  [g] Generate JS  [q] Quit")
        choice = input("> ").strip().lower()
        if choice == "a":
            config = add_page(config)
            save_config(config)
            print("Config saved.")
        elif choice == "g":
            js_dir = JS_DIR
            js_dir.mkdir(parents=True, exist_ok=True)
            js = generate_js(config)
            # Backup existing file before overwriting
            if PAGE_CONFIG_FILE.exists():
                backup = PAGE_CONFIG_FILE.with_suffix(".js.bak")
                backup.write_text(PAGE_CONFIG_FILE.read_text(encoding="utf-8"), encoding="utf-8")
            PAGE_CONFIG_FILE.write_text(js, encoding="utf-8")
            print(f"Generated: {PAGE_CONFIG_FILE}")
        elif choice == "q":
            break


if __name__ == "__main__":
    main()
